CREATE USER IF NOT EXISTS 'test'
IDENTIFIED WITH mysql_native_password BY 'test-pass'
WITH MAX_QUERIES_PER_HOUR 100
PASSWORD EXPIRE INTERVAL 180 DAY
FAILED_LOGIN_ATTEMPTS 3 PASSWORD_LOCK_TIME 2
ATTRIBUTE '{"fname": "James", "lname": "Pretty"}';

GRANT SELECT ON test_db.* TO 'test';