version: '3.9'
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    env_file:
      - .env

  db:
    image: mysql
    volumes:
      - ~/docker_volumes/mysql:/var/lib/mysql
      - ../test_data:/backup
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env