---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.1"
    name: clickhouse 
  - src: https://github.com/Kraktorist/devops-netology
    scm: git
    version: "vector-role"
    name: vector-role