---
- hosts: clickhouse
  roles:
    - clickhouse
  post_tasks:
    - name: Create log table
      tags: clickhouse_db
      import_tasks: post_tasks/create_log_table.yml  
  vars_files:
    - vars/clickhouse.yml
    - vars/db_connection.yml

- hosts: vector
  pre_tasks:
  - name: Add clickhouse addresses to /etc/hosts
    import_tasks: pre_tasks/hosts.yml
  roles:
    - vector-role
  vars_files:
    - vars/vector.yml
    - vars/db_connection.yml


- hosts: lighthouse
  pre_tasks:
  - name: Put Selinux in Permissive mode
    import_tasks: pre_tasks/selinux.yml
  roles:
    - name: geerlingguy.nginx
      become: yes # required to add new yum repo
    - name: lighthouse-role
  vars_files:
    - vars/nginx.yml
