inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the paarams: section
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              worker01: 
              worker02:
              worker03:
              worker04:  
          kube_control_plane:
            hosts:
              control01: 
          etcd:
            hosts:
              control01: 
  
params:
  # provider specifies the terrafrom-provider which will create node resources
  # available values: "ychosted" and "virtualbox"
  provider: ychosted
  # hosts specification
  # every host must have defined name, cpu, memory, disk, public_ip
  control01:
    name: control01
    cpu: 2
    memory: 2048
    disk: 40
    public_ip: true
  worker01:
    name: worker01
    cpu: 2
    memory: 2048
    disk: 20
    public_ip: true
  worker02:
    name: worker02
    cpu: 2
    memory: 2048
    disk: 20
    public_ip: true
  worker03:
    name: worker03
    cpu: 2
    memory: 2048
    disk: 20
    public_ip: true
  worker04:
    name: worker04
    cpu: 2
    memory: 2048
    disk: 20
    public_ip: true