---
# tasks file for lighthouse-role
- name: Install required packages
  become: true
  ansible.builtin.yum:
    name: "{{ required_packages }}"
- block:
    - name: Get lighthouse distrib
      ansible.builtin.get_url:
        url: "{{ lighthouse_distrib }}"
        dest: ./lighthouse.zip
    - name: Unpack lighthouse archive
      become: true
      ansible.builtin.unarchive:
        src: ./lighthouse.zip
        dest: "{{ nginx_basedir }}"
        remote_src: yes
