---
# tasks file for vector-role
- block:
    - include_tasks:
        file: "{{ lookup('first_found', params) }}"
        apply:
          tags: [install]
      vars:
        params:
          files:
            - "install/{{ ansible_pkg_mgr }}.yml"
            - 'empty.yml'
      
    - name: Redefine vector config name
      tags: vector_config
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/vector
        regexp: 'VECTOR_CONFIG='
        line: VECTOR_CONFIG={{ vector_path_configdir }}{{ vector_path_configfilename }}
    - name: Create vector config
      tags: vector_config
      become: true
      template:
        src: config.j2
        dest: "{{ vector_path_configdir }}{{ vector_path_configfilename }}"
  notify: Start Vector service