FROM centos:7
RUN yum clean all \
  && yum -y install epel-release \
  && yum -y update \
  && yum -y install gcc openssl-devel bzip2-devel libffi-devel zlib-devel make \
  && curl https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz --output Python-3.7.9.tgz \
  && tar xzf Python-3.7.9.tgz && rm -rf Python-3.7.9.tgz \
  && cd Python-3.7.9 && ./configure --enable-optimizations \
  && make altinstall && cd .. && rm -rf Python-3.7.9 \
  && curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" \
  && python3.7 get-pip.py && rm -rf get-pip.py \
