version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - 8000:80

  backend:
    build: ./backend
    links:
      - db
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5