version: "3.9"
services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis
    ports:
      - "4141:4141"
    command:
    - server
    env_file:
      - .atlantis.env
      - .terraform.env
    volumes:
      # these two volumes are required to install terraform plugins from local folder
      # if you don't have access to the Internet
      - "/home/kraktorist/repos/devops-netology/07-terraform-03-basic/assets/.terraform:/modules:ro"
      - "./_terraformrc:/home/atlantis/.terraformrc:ro"
      - "./server.yaml:/etc/atlantis/server.yaml:ro"

  ngrok:
    image: ngrok/ngrok:alpine
    ports:
      - "4040:4040"
    command:
    - http
    - atlantis:4141
    env_file:
      - .ngrok.env
    depends_on:
      - atlantis
