version: "3.9"
services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis
    ports:
      - "4141:4141"
    command:
    - server
    - --gh-user="$${ATL_GH_USER}"
    - --gh-token="$${ATL_GH_TOKEN}"
    - --gh-webhook-secret="$${ATL_GH_WEBHOOK_SECRET}"
    - --repo-allowlist="$${ATL_REPO_LIST}"
    env_file:
      - .atlantis.env
    volumes:
      - "/home/kraktorist/repos/devops-netology/07-terraform-03-basic/assets/.terraform:/modules:ro"
      - "./_terraformrc:/root/.terraformrc:ro"

  ngrok:
    image: ngrok/ngrok:alpine
    ports:
      - "4040:4040"
    command:
    - http
    - atlantis:4141
    env_file:
      - .ngrok.env
    depends_on:
      - atlantis
