---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: 192.168.0.201
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
verifier:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
