volumes:
  data:
  prometheus-data:
  grafana_data:

services:
  storage:
    image: minio/minio:latest
    command: server /data
    restart: always
    expose: 
      - 9000
    environment:
      MINIO_ROOT_USER: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${Storage_Secret:-STORAGE_SECRET_KEY}
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    restart: on-failure
    entrypoint: > 
      /bin/sh -c "      
      /usr/bin/mc config host add storage http://storage:9000 ${Storage_AccessKey-STORAGE_ACCESS_KEY} ${Storage_Secret-STORAGE_SECRET_KEY} &&
      /usr/bin/mc mb --ignore-existing storage/${Storage_Bucket:-data} &&
      /usr/bin/mc policy set download storage/${Storage_Bucket:-data} &&
      exit 0;
      "

  testresult:
    image: ellerbrock/alpine-bash-curl-ssl
    depends_on:
      - storage
      - uploader
      - security
      - createbuckets
    restart: on-failure
    environment:
      S3_HOST: storage
      S3_PORT: 9000
      S3_ACCESS_KEY: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      S3_ACCESS_SECRET: ${Storage_Secret:-STORAGE_SECRET_KEY}
      S3_BUCKET: ${Storage_Bucket:-data}
    volumes:
      - ./tests/entrypoint.sh:/home/download/entrypoint.sh
    entrypoint: 
    - /bin/bash
    - -c
    - /home/download/entrypoint.sh

  # mcshell:
  #   image: minio/mc
  #   depends_on:
  #     - storage
  #   restart: on-failure
  #   entrypoint: > 
  #     /bin/sh -c "sleep 36000"

  uploader:
    build: ./uploader
    depends_on:
      - storage
      - createbuckets
    expose: 
      - 3000
    environment:
      PORT: 3000
      S3_HOST: storage
      S3_PORT: 9000
      S3_ACCESS_KEY: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      S3_ACCESS_SECRET: ${Storage_Secret:-STORAGE_SECRET_KEY}
      S3_BUCKET: ${Storage_Bucket:-data}
    restart: on-failure
  
  security:
    build: ./security
    expose: 
      - 3000
    environment:
      PORT: 3000

  gateway:
    image: nginx
    volumes:
      - ./gateway/api.conf.template:/etc/nginx/conf.d/api.conf.template
    ports:
      - "80:8080"      
    depends_on:
      - storage
      - uploader
      - security
    environment:
      S3_BUCKET: ${Storage_Bucket:-data}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/api.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
