apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fedora
  name: fedora
spec:
  containers:
  - image: fedora
    name: fedora
    command:
    - bash
    - -c
    args: 
    - |
      # Point to the internal API server hostname
      APISERVER=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT
      # Path to ServiceAccount token
      SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
      # Read this Pod's namespace
      NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
      # Read the ServiceAccount bearer token
      TOKEN=$(cat ${SERVICEACCOUNT}/token)
      # Reference the internal certificate authority (CA)
      CACERT=${SERVICEACCOUNT}/ca.crt
      # Explore the API with TOKEN
      curl -sS --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/version
      curl -sS --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/pods