apiVersion: 1
notifiers:
  - name: devops
    type: email
    uid: 22
    org_name: Main Org.
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      addresses: "1@1.ru"
