---
apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: app-namespace
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo $(date) New log entry; sleep 1; done;
    image: busybox
    name: busybox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app-namespace
  name: app-log-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-log-reader-rolebinding
  namespace: app-namespace
subjects:
  - kind: User
    name: developer
roleRef:
  kind: Role
  name: app-log-reader
  apiGroup: rbac.authorization.k8s.io