---
apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: app-namespace
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo $(date) New log entry; sleep 1; done;
    image: busybox
    name: busybox

