---
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Add clickhouse addresses to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.clickhouse }}"
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/latest/vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
            dest: "./vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
        - name: Install vector package
          become: true
          ansible.builtin.yum:
            name:
              - "./vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
          
        - name: Set vector env variables
          become: true
          ansible.builtin.lineinfile:
            path: /etc/default/vector
            regexp: 'VECTOR_CONFIG='
            line: VECTOR_CONFIG=/etc/vector/config.yaml
        - name: Create vector config
          become: true
          ansible.builtin.copy:
            dest: /etc/vector/config.yaml
            content: |
              {{ vector_config | to_nice_yaml(indent=2) }}
      notify: Start Vector service
