$script = <<-EOF
    echo Installing the newest terraform version
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install terraform unzip
    echo Installing terraform v0.12
    curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip
    unzip terraform.zip && rm -rf terraform.zip && mv terraform /usr/bin/terraform0.12
EOF

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.provision "shell", inline: $script
end